name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: change execution type of script
      run: chmod +x ./generate_documentation.sh

    - name: generate latest documentation
      run: ./generate_documentation.sh
      
    - name: 'zipping documentation'
      run: zip -r documentation.zip ./documentation/
      
    - uses: actions/upload-artifact@v2
      with:
        name: generated-documentation
        path: ./documentation.zip
